spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #    type: com.zaxxer.hikari.HikariDataSource
#    filters: stat,wall
    druid:
      aop-patterns: org.zgg.springboot_web_02.*  #springbean监控
      filters: stat,wall,slf4j  #所有开启的功能
      stat-view-servlet:  #监控页配置
        enabled: true
        login-password: 111
        login-username: admin
      web-stat-filter:  #web监控
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/sql/*'
      filter:
        stat:  #sql监控
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:  #防火墙
          enabled: true
          config:
            drop-table-allow: false

  jdbc:
    template:
      query-timeout: 3
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true
  application:
    name: springboot_web_02


#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

# management 是所有actuator的配置
# management.endpoint.端点名.xxxx  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true  #默认开启所有监控端点  true
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点

  endpoint:   #对某个端点的具体配置
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: springboot_web_02
  mavenProjectVersion: 0.0.1-SNAPSHOT